version: "3.4"

x-rnode: &default-rnode
  image: coop.rchain/rnode:latest
  user: root
  restart: always
  networks:
    - rchain-net

x-wait-rnode: &wait-rnode
  build: .
  user: root
  restart: always
  networks:
    - rchain-net

services:
  boot:
    <<: *default-rnode
    container_name: rnode.boot
    command: run -s --validator-private-key=4d969f43affa8e5c47900e6db475cb8ddd8520170ee73b2207c54014006ff2b --host rnode.boot --allow-private-addresses -n --synchrony-constraint-threshold 0 --wallets-file /var/lib/rnode/wallets.txt --bonds-file /var/lib/rnode/bonds.txt --deploy-timestamp 1 --required-sigs 2 --duration 1min --interval 10sec
    volumes:
      - ./wallets.txt:/var/lib/rnode/wallets.txt
      - ./bonds.txt:/var/lib/rnode/bonds.txt
      - ./node.certificate.pem:/var/lib/rnode/node.certificate.pem
      - ./node.key.pem:/var/lib/rnode/node.key.pem

  validator1:
    <<: *wait-rnode
    container_name: rnode.validator1
    entrypoint: ["/bin/bash"]
    command: ["/wait.sh", "rnode.boot", "40404", "--", 
    "/opt/docker/bin/rnode run -b rnode://5b0390a7c34319310de2432cc2c9dc433043783e@rnode.boot?protocol=40400&discovery=40404 --validator-private-key=016120657a8f96c8ee5c50b138c70c66a2b1366f81ea41ae66065e51174e158e --host rnode.validator1 --allow-private-addresses -n --synchrony-constraint-threshold 0 --genesis-validator --deploy-timestamp 1 --required-sigs 2 --wallets-file /var/lib/rnode/wallets.txt --bonds-file /var/lib/rnode/bonds.txt"]
    volumes:
      - ./wallets.txt:/var/lib/rnode/wallets.txt
      - ./bonds.txt:/var/lib/rnode/bonds.txt
      - ./wait.sh:/wait.sh

  validator2:
    <<: *wait-rnode
    container_name: rnode.validator2
    entrypoint: ["/bin/bash"]
    command: ["/wait.sh", "rnode.boot", "40404", "--",
    "/opt/docker/bin/rnode run -b rnode://5b0390a7c34319310de2432cc2c9dc433043783e@rnode.boot?protocol=40400&discovery=40404 --validator-private-key=304b2893981c36122a687c1fd534628d6f1d4e9dd8f44569039ea762dae2d3e7 --host rnode.validator2 --allow-private-addresses -n --synchrony-constraint-threshold 0 --genesis-validator --deploy-timestamp 1 --required-sigs 2 --wallets-file /var/lib/rnode/wallets.txt --bonds-file /var/lib/rnode/bonds.txt"]
    volumes:
      - ./wallets.txt:/var/lib/rnode/wallets.txt
      - ./bonds.txt:/var/lib/rnode/bonds.txt
      - ./wait.sh:/wait.sh

networks:
  rchain-net:
