version: "3.3"

services:
  propose:
    image: coop.rchain/rnode:0.0.1-76-gb0b3545
    command: ["--config", "/proposer_config.yml"]
    volumes:
      - ./resources/nil.rho:/nil.rho
      - ./resources/hello_world_again.rho:/hello_world_again.rho
      - ./resources/simpleInsertTest.rho:/simpleInsertTest.rho
      - ./resources/simpleLookupTest.rho:/simpleLoopupTest.rho
      - ./resources/simpleInsertLookup.rho:/simpleInsertLookup.rho
      - ./resources/proposer_config.yml:/proposer_config.yml
    networks:
      - rchain-net
networks:
  rchain-net:
